# 100 MHz clock from Arty A7 onboard oscillator
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVCMOS33 } [get_ports { clk100 }]; # Sch=gclk[100]
# 100 MHz input clock from Arty oscillator
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk100 }];

# 25 MHz derived clock (generated by clock divider in top.v, divide by 4)
create_generated_clock -name clk25 -source [get_ports clk100] -divide_by 4 [get_pins clk_div_reg[1]/Q]

## Switches (we only need SW0 and SW1)
set_property -dict { PACKAGE_PIN A8  IOSTANDARD LVCMOS33 } [get_ports { sw[0] }]; # Sch=sw[0]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports { sw[1] }]; # Sch=sw[1]

## LEDs (we use LED[3:0])
## Bright LEDs (using GREEN channels of LD0-LD3)
set_property -dict { PACKAGE_PIN F6 IOSTANDARD LVCMOS33 } [get_ports { led[0] }]; # LD0 Green
set_property -dict { PACKAGE_PIN J4 IOSTANDARD LVCMOS33 } [get_ports { led[1] }]; # LD1 Green
set_property -dict { PACKAGE_PIN J2 IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; # LD2 Green
set_property -dict { PACKAGE_PIN H6 IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; # LD3 Green


## Buttons (BTN0 = step, BTN1 = reset)
set_property -dict { PACKAGE_PIN D9 IOSTANDARD LVCMOS33 } [get_ports { btn0 }]; # Sch=btn[0]
set_property -dict { PACKAGE_PIN C9 IOSTANDARD LVCMOS33 } [get_ports { btn1 }]; # Sch=btn[1]

# UART: FPGA TX->PC on D10, FPGA RX<-PC on A9
set_property -dict { PACKAGE_PIN D10 IOSTANDARD LVCMOS33 DRIVE 12 SLEW FAST } [get_ports { uart_tx }];
set_property -dict { PACKAGE_PIN A9  IOSTANDARD LVCMOS33 } [get_ports { uart_rx }];



